### ISSUE TITLE
Reimplement `r0`, since it is deprecated

### ISSUE THREAD

**Issue by coastalwhite** [rust-embedded/riscv-rt#122]
This repository should find an alternative to `r0`, since that crate is now archived and deprecated.

**Comment by romancardenas** [comment]
Thanks for opening this issue! I'll take a look. Of course, PRs are more than welcome :)

**Comment by coastalwhite** [comment]
I’ll have a look at this. Is there a preference for a separate crate again or should it just become a part of the `riscv-rt` crate?

**Comment by romancardenas** [comment]
I prefer to reduce the number of dependencies, but if you find a handy crate that eases the work, then use it.

If I were you, I'd implement it in assembly.

**Comment by adamgreig** [comment]
The conclusion when we deprecated `r0` was that this can only soundly be implemented in assembly; cortex-m-rt does so [here](https://github.com/rust-embedded/cortex-m/blob/1746a63ca16b68514ea23dcca1543aed00165452/cortex-m-rt/src/lib.rs#L517-L552). I think it's best put into your existing startup routine ([here](https://github.com/rust-embedded/riscv-rt/blob/8bda5c228079c7ac853e8b973a16b575bafe7708/src/asm.rs#L25)).

**Comment by romancardenas** [comment]
i see you feature-gate the RAM initialization. Would you recommend us to do the same for `riscv-rt`?

**Comment by romancardenas** [comment]
We can get some inspiration from the `esp-hal` folks: https://github.com/esp-rs/esp-hal/blob/eeb2d1db6f8ffd250b212bd1bebaddc83d0ea8b0/esp-riscv-rt/src/lib.rs#L294C8-L294C8

**Comment by adamgreig** [comment]
> I see you feature-gate the RAM initialization. Would you recommend us to do the same for `riscv-rt`?

That was a later addition from users with MCUs that have things like ECC RAM where you have to write to the entire RAM at startup to initialise the memory controller; usually it's enough to just initialise the .data and .bss sections and leave unused RAM alone. Since there's a startup time cost, it made sense to feature-gate this just for users who need it.

I think you could reasonably support the same feature, but just doing .data and .bss is enough for almost all use cases.
